### PR TITLE
Use `repl-prompt` parameter value for nrepl prompt

### LINKED ISSUE #5: Customizable prompt, change default
It'd be nice if the default prompt was `#;>` rather than `;>`, as I think that's more consistent with the default `csi` prompt. Additionally, the former works better `M-x run-scheme`, since `#;` will comment out just the `>`, while with `;>` the whole line is treated as a comment.

Also, we could export the `nrepl-prompt` parameter to make it customizable! What do you think?

### PR DESCRIPTION
**Pull request by dieggsy**
- Orignially by @evhan
- Fixes #5

### CODE REVIEW

**Comment by dieggsy** [comment]
Let me know what you think. I suppose the version should be bumped for this change to be distributed through `chicken-install`

**Comment by evhan** [comment]
Looks like it was changed back in 07480b06, @kristianlm can probably say why.

FWIW, regarding that commit, there oughtn't be a number in the prompt unless `repl` is used within `csi`, since that defines its a prompt that includes the history. The default value from `(chicken repl)` just prints `"#;> "`.

**Comment by dieggsy** [comment]
Oh, thanks, I didn't see that. Hmm. Maybe my original suggestion of changing the default and exposing the parameter would be better if there was some problem with using repl-prompt

**Comment by kristianlm** [comment]
sorry for the late reply, I've fixed my github email notification settings so hopefully I'll be more prompt from now on :-)

the commit @evhan mentions says why: 

> fix: use separate nrepl-prompt
>
> because the built-in one is wrong. it shows a counter, but it's never incremented.

This makes my default nrepl prompt look like this:

```
$ nc localhost 1234
;; nrepl on (csi -R nrepl -e (nrepl 1234))
#;1> 1
1
#;1> 2
2
```
And I think that's ugly and misleading. We have some options:

1. change nrepl-prompt to `#;>`
2. ignore the 1 in `#;1>` (merge)
3. actually make it work like `chicken.repl#repl` and increment that counter (how much work is that?)

I was never a fan of the `#1` returns from the repl, but if it's not much work that sounds like a good option.

**Comment by evhan** [comment]
Personally, I like option one (as well as exporting the `nrepl-prompt` parameter).

Option two would be confusing, and option three would probably either require changes to csi itself or reimplementing the relevant logic in nrepl. The first of these could be done (I'll take a closer look and create a ticket if it seems worth doing) but the second probably isn't what you want.

**Comment by dieggsy** [comment]
I like option one too + exporting the param too, I think. If option three wasn't too much work to implement, some might consider this more consistent with csi? Dunno. In any case, I'll close this PR so we can move on to a more fitting approach.

**Comment by kristianlm** [comment]
Thanks for your feedback. Version 5.0.7 should be out soon with the changes in option 1.

```
1021 klm@kth ~  ➤ csi -R nrepl -e '(nrepl-prompt (lambda () (display "ohoh> ")))(nrepl-loop)'
ohoh> 123
123
```

@evhan let me know how option 3 might come along if you have time to look into the `csi` internals!

**Pull request closed without merging**
